version: "3.8"

services:
  database:
    env_file:
      - .env
    container_name: mysql
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "Asia/Seoul"
      MYSQL_ENCODING: "UTF-8"
    volumes:
      - ./usr/local/mysql/data:/var/lib/mysql

  application:
    env_file:
      - .env
    container_name: dantong
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: ${MYSQL_DB}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "Asia/Seoul"
    depends_on:
      - database