spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${database.url}
    username: ${mysql.user}
    password: ${mysql.password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 200
        format_sql: true
        show_sql: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mvc:
    pathmatch:
      matching-strategy:
        ant-path-matcher
  data:
    redis:
      host: ${redis.url}
      port: 15620
      password: ${redis.password}
      url: redis://${redis.password}@${redis.url}:15620
  messages:
    basename: messages/messages

security:
  jwt:
    token:
      secret-key: ${JWT-KEY}
      expire-length: P1D
      expire-length-refresh: P15D
nhn:
  email:
    url: ${nhn.url}
    secret-key: ${nhn.secret-key}
    sender-mail: ${sender.mail}
app:
  auth:
    email:
      code-length: 6
    signup-expires: PT1H
  cors: "*"
cloud:
  aws:
    s3:
      bucketName: dantong
    region:
      static: ap-southeast-2
    credentials:
      access-key: ${aws.s3.access-key}
      secret-key: ${aws.s3.secret-key}
    stack:
      auto: false

file:
  path: ${user.home}/